name: signup_signin_temp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"
#------------- PACKAGES Start--------------#
dependencies:
  flutter:
    sdk: flutter
  # Utitlity Packages

  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  url_launcher: ^6.2.4
  intl: ^0.19.0
  http: ^1.2.0
  get_storage: ^2.1.1
  logger: ^2.0.2+1

  # Product Specific Packages

#------------- PACKAGES END--------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  #------------- LOCAL ASSETS --------------#
  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/brands/
#------------- LOCAL ASSETS END --------------#

#------------- FONTS --------------#
fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800
